### ISSUE TITLE
Does not work with Zotero 5.0.96.2

### ISSUE THREAD

**Issue by austinlines** [MagTun/katex_for_zotero#1]
I was unable to get this working for Zotero 5.0.96.2. Is there additional steps I need to take/other packages I need to download other than what's provided on this GitHub page?

**Comment by MagTun** [comment]
Everything that you need to do is described on the [main page](https://github.com/MagTun/katex_for_zotero): nothing else that the plugin need to be downloaded. 

I have just updated zotero to get the 5.0.96.2 version and for me it's working. 

Are you sure that the edits in ` note.html` were saved, as sometimes, there are not (depending on how you close the file/text editor after editing it)?

**Comment by austinlines** [comment]
Ok. Sorry. Probably something that I'm doing wrong. I just get the error:

"Failed to load plugin: katex_for_zotero from url resource://zotero/tinymce/plugins/katex_for_zotero/plugin.min.js"

Thanks for your help. I'm new to GitHub, so I apologize for posting this publicly. Is there any way to PM about this problem?

**Comment by MagTun** [comment]
It's okay that's how Github works: it's made for public feedbacks/debugging so that anyone can benefit from it.

Thanks for giving the whole debug as I could found the error. And actually it's me who apologize because I made a mistake. 

The file `plugin.js` in the folder `katex_for_zotero` should actually be called `plugin.min.js`. Sorry for that and for the time you spent on trying to make this plugin work. 

Let me know if this is working. 

Also if you don't know it yet, Zotero is going to switch to Prosemirror by the end of the year and this plugin will not work anymore as it is based on HTML.

**Comment by austinlines** [comment]
Thank you so much for your quick response. I suppose I should have been
able to figure that out for myself, but thank you! It works perfectly now.

I did not know they were switching. Thanks for the heads up!

**Comment by MagTun** [comment]
You are welcome!
